spring.application.name=patient-service

# PostgreSQL Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/patientdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
hibernate.jdbc.time_zone=Asia/Kolkata


# IMPORTANT FOR data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Server Port
server.port=${SERVER_PORT:4000}

# gRPC
grpc.client.billing-service.address=${GRPC_CLIENT_BILLING_SERVICE_ADDRESS:static://billing-service:9001}
grpc.client.billing-service.negotiation-type=plaintext

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
app.kafka.topic.patient-created=patient.created
